#!/bin/bash


# ==========================================
# os specific
# ==========================================
export xargs_command="xargs --no-run-if-empty "
case "$(uname -s)" in

   Darwin)
     export xargs_command="xargs "
     export ABSPATH=`pwd -P`
     ;;

   Linux)
     export ABSPATH=`dirname $(readlink -f $0)`
     ;;

   CYGWIN*|MINGW32*|MSYS*)
     export ABSPATH=`dirname $(readlink -f $0)`
     ;;

   *)
     export ABSPATH=`dirname $(readlink -f $0)`
     ;;
esac




# ==========================================
# check if we are in right place
# ==========================================
cd $ABSPATH/
if [[ -f devlab && -f ../Dockerfile  ]]
then
	true
else
	echo "Oops! I do not know where i am :/"
    exit;
fi






# ==========================================
# prepare dev data folder
# ==========================================
mkdir /tmp/home 2>/dev/null
mkdir /tmp/home/user 2>/dev/null
if [ ! -d /tmp/home/user ]
then
    echo "Oops! Fail create /tmp/home/user :/"
    exit;
fi



# ==========================================
# some functions
# ==========================================
print_usage() {
	echo "=========================================="
	echo "development lab"
	echo "=========================================="
	echo ""
	echo "usage: $0 <command>"
	echo ""
	echo "commands:"
	echo "  status  -> display status"
	echo "  start   -> start development instance"
	echo "  stop    -> stop development instance"
	echo "  log     -> tail instance log"
	echo "  rebuild -> destroy and build development instance"
	echo "  destroy -> destroy development instance"
	echo "  console -> access console at development instance"
}
set_active_instance_id() {
	#
	active_id=;
	#
	now_id=`docker ps | tail -n +2 | awk '{print $1,$2}' | grep docker-remote-desktop | awk '{print $1}'  | head -n 1 `
	#now_id=""
	#echo "now_id=$now_id"
	if [ -z $now_id ]; then
		#echo "no now_id"
		return 1
	fi
	#
	now_status=`docker inspect --format '{{ .State.Running }}' $now_id`
	#echo "now_status=$now_status"
	if [ $now_status == "true" ]; then
		active_id=$now_id;
		return 0
	fi
	#
	#echo "not running now_status"
	return 1
}





# =====================================================================
# actions
# =====================================================================
#
# empty
if [ -z "$1" ];  then
	print_usage
	echo ""
	exit;
fi
#
if [ $1 == "status" ]; then
	set_active_instance_id
	if [ -z $active_id ]; then
		echo "No running instance"
	else
		echo "We have a running instance id=$active_id"
	fi
	exit;
fi
#
if [ $1 == "log" ]; then
	set_active_instance_id
	if [ -z $active_id ]; then
		echo "No running instance"
	else
		echo "log instance id=$active_id"
		docker logs -f -t $active_id
	fi
	exit;
fi
#
if [ $1 == "rebuild" ]; then
	docker ps | tail -n +2 | awk '{print $1,$2}' | grep docker-remote-desktop | awk '{print $1}' | $xargs_command docker kill
	docker ps -a | tail -n +2 | awk '{print $1,$2}' | grep docker-remote-desktop | awk '{print $1}' | $xargs_command docker rm
	docker images | tail -n +2 | grep docker-remote-desktop | awk '{print $3}' | $xargs_command docker rmi -f
	cd ..
	docker build -t docker-remote-desktop .
	exit;
fi
#
if [ $1 == "build" ]; then
	docker ps | tail -n +2 | awk '{print $1,$2}' | grep docker-remote-desktop | awk '{print $1}' | $xargs_command docker kill
	docker ps -a | tail -n +2 | awk '{print $1,$2}' | grep docker-remote-desktop | awk '{print $1}' | $xargs_command docker rm
	docker images | tail -n +2 | grep docker-remote-desktop | awk '{print $3}' | $xargs_command docker rmi -f
	cd ..
	docker build -t docker-remote-desktop .
	exit;
fi
#
if [ $1 == "push" ]; then
	docker ps | tail -n +2 | awk '{print $1,$2}' | grep "neyfrota/docker-remote-desktop" | awk '{print $1}' | $xargs_command docker kill
	docker ps -a | tail -n +2 | awk '{print $1,$2}' | grep "neyfrota/docker-remote-desktop" | awk '{print $1}' | $xargs_command docker rm
	docker images | tail -n +2 | grep "neyfrota/docker-remote-desktop" | awk '{print $3}' | $xargs_command docker rmi -f
	cd ..
	docker build -t neyfrota/docker-remote-desktop .
	docker push neyfrota/docker-remote-desktop
	exit;
fi
#
if [ $1 == "destroy" ]; then
	echo "We need SU permission to remove /tmp/docker-remote-desktop"
	#sudo rm -Rf /tmp/docker-remote-desktop
	docker ps -a | tail -n +2 | awk '{print $1,$2}' | grep docker-remote-desktop | awk '{print $1}' | $xargs_command docker kill
	docker ps -a | tail -n +2 | awk '{print $1,$2}' | grep docker-remote-desktop | awk '{print $1}' | $xargs_command docker rm
	docker images | tail -n +2 | grep docker-remote-desktop | awk '{print $3}' | $xargs_command docker rmi -f
	exit;
fi
#
if [ $1 == "start" ]; then
	set_active_instance_id
	if [ -z $active_id ]; then
		echo "No running instance, Lets start"
		cd ..
		docker run -d -e "development=true" -p 22:22 -e "pubkey=$(cat ~/.ssh/id_rsa.pub)" -v /tmp/home:/home neyfrota/docker-remote-desktop
		set_active_instance_id
		if [ -z $active_id ]; then
			echo "Fail start. No running instance"
		else
			echo "New running instance id=$active_id"
		fi
	else
		echo "We have a running instance id=$active_id"
	fi
	exit;
fi
#
if [ $1 == "stop" ]; then
	docker ps | tail -n +2 | awk '{print $1,$2}' | grep docker-remote-desktop | awk '{print $1}' | $xargs_command docker kill
	set_active_instance_id
	if [ -z $active_id ]; then
		echo "No running instance"
	else
		echo "Fail stop. We still have a running instance id=$active_id"
	fi
	exit;
fi
#
if [ $1 == "console" ]; then
	set_active_instance_id
	if [ -z $active_id ]; then
		echo "No running instance"
	else
		echo "Connecting to instance id=$active_id"
		docker exec -i -t $active_id /bin/bash
	fi
	exit;
fi
#
